### ISSUE TITLE
Unable to get week date.

### ISSUE THREAD

**Issue by yeahnoob** [andelf/weather-rs#2]
As the captured Screenshots in README, it cannot get the week date information correctly.
是否因为 time 模块功能有限制？

```
let date_fmt = "┤ ".to_string() + strftime("%a %d. %b", strptime(&self.date, "%Y-%m-%d").as_ref().unwrap()).as_ref().unwrap() + " ├";
```

**Comment by andelf** [comment]
`strptime()` 函数只是做解析，不做判断处理，不能保证得到的结构可用。
需要调用 `to_local()` 处理。
