### ISSUE TITLE
error: cannot borrow immutable local variable `client` as mutable

### ISSUE THREAD

**Issue by singpenguin** [andelf/weather-rs#3]
src/main.rs:523:19: 523:25 error: cannot borrow immutable local variable `client` as mutable
src/main.rs:523     let mut res = client.get(url).send().unwrap();
                                  ^~~~~~
error: aborting due to previous error
Could not compile `weather`.

replace line 521 let mut client = Client::new();

**Comment by andelf** [comment]
`cargo update` to newest `hyper`
or 
`git checkout HEAD~1` some version before also works
:) 

https://github.com/andelf/weather-rs/commit/886411cc384fdc18c4e742d9daec4554332df51f
